### ISSUE TITLE
Automatically refresh core data on people via Active Directory

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-People-Directory#35]
All of the data attached to people that is initially pulled from active directory should be refreshed on a regular schedule.

**Comment by philcable** [comment]
I've been thinking that it might be best to handle this piece in the child theme. Thoughts?

**Comment by jeremyfelt** [comment]
I think that makes sense. It could even work to create another plugin for it, but having it in the child theme first will help guide where it should go.

**Comment by philcable** [comment]
Moving this to https://github.com/washingtonstateuniversity/people.wsu.edu/issues/16.
