### ISSUE TITLE
UI hides selection when selecting multiple terms for a taxonomy in Select2

### ISSUE THREAD

**Issue by jeremyfelt** [washingtonstateuniversity/WSU-People-Directory#84]
I don't think this is too far off, but it feels a little weird. That my additional choices were selected wasn't always obvious to me.

![select2-taxonomy-multiple](https://user-images.githubusercontent.com/286171/27140025-5d7e9332-50d9-11e7-946b-a256eb2ce6dc.gif)

**Comment by philcable** [comment]
I noticed that scrolling triggers a reposition of the dropdown, so it shouldn't be too much trouble to fix this.
